# AutoPFX MIT license 2024
# https://github.com/Canmi21/AutoPFX/
# Copyright (C) Canmi(Canmi21), all right reserved.

PFX: PFX
#PFX Location.

SignToolPath: C:\Program Files (x86)\Windows Kits\10\App Certification Kit\signtool.exe
#SignTool.exe

TimeStampUrl: "http://timestamp.digicert.com"
#Server

#OpenSSL: C:\Program Files\OpenSSL-Win64\bin\openssl.exe
#Location